import { DaDataAddress, DaDataSuggestion } from "react-dadata";

type GeoData = {
  city: string;
  street: string;
  house: string;
  geo_lat: string;
  geo_lon: string;
};

const nullValue = {
  area: null,
  area_fias_id: null,
  area_kladr_id: null,
  area_type: null,
  area_type_full: null,
  area_with_type: null,
  beltway_distance: null,
  beltway_hit: null,
  block: null,
  block_type: null,
  block_type_full: null,
  federal_district: null,
  city_area: null,
  city_district: null,
  city_district_fias_id: null,
  city_district_kladr_id: null,
  city_district_type: null,
  city_district_type_full: null,
  city_district_with_type: null,
  city_fias_id: null,
  city_kladr_id: null,
  city_type: null,
  city_type_full: null,
  city_with_type: null,
  flat: null,
  flat_area: null,
  flat_price: null,
  flat_type: null,
  flat_type_full: null,
  flat_fias_id: null,
  flat_cadnum: null,
  geoname_id: null,
  history_values: null,
  house_fias_id: null,
  house_kladr_id: null,
  house_type: null,
  house_type_full: null,
  house_cadnum: null,
  entrance: null,
  floor: null,
  okato: null,
  oktmo: null,
  postal_box: null,
  postal_code: null,
  qc: null,
  qc_complete: null,
  qc_geo: null,
  qc_house: null,
  settlement: null,
  settlement_fias_id: null,
  settlement_kladr_id: null,
  settlement_type: null,
  settlement_type_full: null,
  settlement_with_type: null,
  source: null,
  square_meter_price: null,
  street_fias_id: null,
  street_kladr_id: null,
  street_type: null,
  street_type_full: null,
  street_with_type: null,
  stead: null,
  stead_fias_id: null,
  stead_kladr_id: null,
  stead_type: null,
  stead_type_full: null,
  stead_cadnum: null,
  tax_office: null,
  tax_office_legal: null,
  timezone: null,
  unparsed_parts: null,
  metro: null,
  divisions: null,
};

export const adaptToDaDataSuggestion = (address: string, geoData: GeoData): DaDataSuggestion<DaDataAddress> => {
  return {
    value: address,
    unrestricted_value: address,
    data: {
      ...nullValue,
      ...geoData,

      capital_marker: "0",
      fias_level: "",
      country: "Россия",
      country_iso_code: "RU",
      fias_id: "",
      kladr_id: "",
      region: "",
      region_fias_id: "",
      region_kladr_id: "",
      region_type: "",
      region_type_full: "",
      region_with_type: "",
      fias_code: "",
      region_iso_code: "",
      fias_actuality_state: "",
    },
  };
};
